test: &test
  adapter: postgresql
  database: object_diff_trail_test
  username: postgres
  password:
  host:     localhost
  port:     5432

foo:
  <<: *test
  database: object_diff_trail_foo

bar:
  <<: *test
  database: object_diff_trail_bar
